Repository endermAH/Dungeons_d, pull requests merged in 2020-07, with the labels that each got.

#19 Feature/dung 13
  .gitignore
  Assets/Prefabs/Chest.prefab
  Assets/Prefabs/highlighter.prefab
  Assets/Prefabs/highlighter.prefab.meta
  Assets/Scripts/Chest/OpenChest.cs
  Assets/Scripts/Player/PlayerStats.cs
  Assets/Sprites/Dungeon_Tileset/Chests/Common/highlighter.png
  Assets/Sprites/Dungeon_Tileset/Chests/Common/highlighter.png.meta
Labels: enhancement

#21 Feature/dung 7
  Assets/Scripts/Common/README.md
  Assets/Scripts/Common/README.md.meta
  Assets/Scripts/Enemy/README.md
  Assets/Scripts/Enemy/README.md.meta
  Assets/Scripts/Languages/README.md
  Assets/Scripts/Languages/README.md.meta
  Assets/Scripts/Menu/README.md
  Assets/Scripts/Menu/README.md.meta
  Assets/Scripts/Player/README.md
  Assets/Scripts/Player/README.md.meta
  Assets/Scripts/WeaponControl/README.md
  Assets/Scripts/WeaponControl/README.md.meta
Labels: documentation

#23 Develop
  .idea/.idea.Dungeons_d/.idea/indexLayout.xml
  .idea/.idea.Dungeons_d/riderModule.iml
  Assets/Prefabs/MiniElf_m.prefab
  Assets/Scenes/level1.unity
  Assets/Scripts/Common/LineOfSight.cs
  Assets/Scripts/Common/LineOfSight.cs.meta
  Assets/Scripts/Enemy/SimpleEnemyAI.cs
  Assets/Scripts/Enemy/SimpleEnemyAI.cs.meta
Labels: bug
